# Usa una imagen base de Python
FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo requirements.txt y el código fuente
COPY requirements.txt .
COPY . .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 8000
EXPOSE 8000

# Define el comando de inicio
CMD ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
