"""
Django settings for upcyclewear project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
import cx_Oracle


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ASGI_APPLICATION = 'upcyclewear.asgi.application'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ac9p#k9s=su2j*6p9y#t8(v0_vlg+9cgae82h!9^(%r6$!c48l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aplicacion',
    'channels',
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'upcyclewear.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'upcyclewear.wsgi.application'


# Database


import os
import cx_Oracle

# Obtiene la ruta del directorio base del proyecto
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Inicializa el cliente de Oracle
instant_client_path = os.path.join(BASE_DIR, 'instantclient')
cx_Oracle.init_oracle_client(lib_dir=instant_client_path)

# Path to the wallet directory
wallet_path = os.path.join(BASE_DIR, 'wallet')
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': (
            '(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=adb.sa-santiago-1.oraclecloud.com)(PORT=1522))'
            '(CONNECT_DATA=(SERVICE_NAME=g2abc6effbe7f19_upcyclewear_high.adb.oraclecloud.com)))'
        ),
        'USER': 'ADMIN',  # Tu usuario de la base de datos
        'PASSWORD': 'SecurePass1234',  # Tu contraseña
        'OPTIONS': {
            'threaded': True,  # Permite conexiones en múltiples hilos
        },
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'g2abc6effbe7f19_upcyclewear_high.adb.oraclecloud.com',  # Por ejemplo: g2abc6effbe7f19_upcyclewear_high.adb.oraclecloud.com
        'USER': 'ADMIN',  # Tu usuario de la base de datos
        'PASSWORD': 'SecurePass1234',  # Tu contraseña
        'HOST': 'adb.sa-santiago-1.oraclecloud.com',  # Host del servicio
        'PORT': '1522',  # Puerto
        'OPTIONS': {
            'threaded': True,  # Permite conexiones en múltiples hilos
        },
    }
}






# Otras configuraciones de Django...

"""
sqlplus c##superuser/hola1234@localhost:1521/XE



BEGIN
FOR t IN (SELECT table_name FROM user_tables) LOOP
EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
END LOOP;
END;
 /
  """
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# settings.py

LANGUAGE_CODE = 'en-us'  # Mantener el idioma general como inglés

TIME_ZONE = 'America/Santiago'  # Zona horaria de Chile

USE_I18N = True
USE_L10N = False  # Desactivar la localización para usar el formato personalizado
USE_TZ = True

# Formato de fecha personalizado
DATE_FORMAT = 'd/m/Y'  # Formato de fecha chileno DD/MM/AAAA
TIME_FORMAT = 'H:i:s'   # Formato de hora (24 horas)
DATETIME_FORMAT = 'd/m/Y H:i:s'  # Formato de fecha y hora

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'aplicacion.Usuario'

#PARA LA CARGA DE IMAGENES

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ["redis://:keKFnERQHWkLxamOz0EA613CYf79E2aF@redis-18884.c336.samerica-east1-1.gce.redns.redis-cloud.com:18884"],
        },
    },
}


"""
SETINGS REDIS ANTIGUO
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
"""

# configs correo:

# Configuración del envío de correos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'upcyclewearcl@gmail.com' 
EMAIL_HOST_PASSWORD = 'oytm zmdh xhbi nuux' 


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django_error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
        },
        'yourapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}
