# Generated by Django 5.1.1 on 2024-11-09 04:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, default='img/nofoto.jpg', null=True, upload_to='perfiles/')),
                ('descripcion', models.TextField(blank=True)),
                ('facebook', models.URLField(default='https://www.facebook.com/')),
                ('instagram', models.URLField(default='https://www.instagram.com/')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/')),
                ('total_donaciones', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario1', 'usuario2')},
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_ropa', models.CharField(choices=[('', 'Seleccione una opción'), ('Ropa Superior', [('camiseta', 'Camiseta'), ('polo', 'Polo'), ('blusa', 'Blusa'), ('camisa', 'Camisa'), ('top', 'Top'), ('sueter', 'Suéter'), ('sudadera', 'Sudadera'), ('chaqueta', 'Chaqueta'), ('abrigo', 'Abrigo'), ('cardigan', 'Cárdigan'), ('chaleco', 'Chaleco'), ('camiseta_sin_mangas', 'Camiseta sin mangas'), ('blazer', 'Saco o Blazer'), ('jersey', 'Jersey')]), ('Ropa Inferior', [('pantalon', 'Pantalón'), ('falda', 'Falda'), ('shorts', 'Shorts'), ('bermudas', 'Bermudas'), ('leggings', 'Leggings'), ('capris', 'Capris')]), ('Vestidos', [('vestido_fiesta', 'Vestido de Fiesta'), ('vestido_casual', 'Vestido Casual'), ('vestido_noche', 'Vestido de Noche'), ('vestido_largo', 'Vestido Largo'), ('vestido_corto', 'Vestido Corto'), ('vestido_coctel', 'Vestido de Cóctel'), ('maxi_vestido', 'Maxi Vestido')]), ('Ropa Íntima', [('sujetador', 'Sujetador'), ('calzoncillos', 'Calzoncillos'), ('bragas', 'Bragas'), ('bodysuit', 'Bodysuit'), ('camiseta_interior', 'Camiseta interior'), ('faja', 'Faja'), ('corset', 'Corset'), ('camison', 'Camisón'), ('pijama', 'Pijamas'), ('batas_dormir', 'Batas de dormir')]), ('Ropa de Exterior', [('abrigo', 'Abrigo'), ('chaqueta', 'Chaqueta'), ('gabardina', 'Gabardina o Trench'), ('parka', 'Parka'), ('poncho', 'Poncho'), ('capa', 'Capa'), ('impermeable', 'Impermeable'), ('chaleco_acolchado', 'Chaleco acolchado')]), ('Ropa Deportiva', [('sudadera', 'Sudadera'), ('pantalon_deportivo', 'Pantalón deportivo'), ('shorts_deportivos', 'Shorts deportivos'), ('leggings_deportivos', 'Leggings deportivos'), ('top_deportivo', 'Top deportivo'), ('traje_bano', 'Traje de baño'), ('bikini', 'Bikini'), ('ropa_ciclismo', 'Ropa de ciclismo'), ('ropa_yoga', 'Ropa de yoga')]), ('Ropa de Bebé', [('body', 'Body'), ('pelele', 'Pelele'), ('mameluco', 'Mameluco'), ('babero', 'Babero'), ('pantalones_bebe', 'Pantalones para bebé'), ('conjuntos_bebe', 'Conjuntos'), ('polainas', 'Polainas'), ('pijamas_bebe', 'Pijamas para bebé'), ('chaleco_acolchado_bebe', 'Chaleco acolchado para bebé')]), ('Trajes', [('traje_dos_piezas', 'Traje de dos piezas'), ('esmoquin', 'Esmoquin'), ('traje_tres_piezas', 'Traje de tres piezas'), ('conjunto_falda', 'Conjunto de falda y chaqueta'), ('conjunto_pantalon', 'Conjunto de pantalón y top')]), ('Accesorios de Ropa', [('bufanda', 'Bufanda'), ('guantes', 'Guantes'), ('sombrero', 'Sombrero'), ('cinturon', 'Cinturón'), ('panuelo', 'Pañuelo'), ('calcetines', 'Calcetines'), ('ligas', 'Ligas'), ('chal', 'Chal')]), ('Uniformes', [('uniforme_escolar', 'Uniforme escolar'), ('uniforme_trabajo', 'Uniforme de trabajo'), ('ropa_enfermeria', 'Ropa de enfermería'), ('uniforme_deportivo', 'Uniforme deportivo'), ('traje_proteccion', 'Traje de protección'), ('uniforme_militar', 'Uniforme militar')]), ('Trajes Tradicionales', [('kimono', 'Kimono'), ('sari', 'Sari'), ('traje_folclorico', 'Traje folclórico'), ('traje_flamenco', 'Traje de flamenco'), ('traje_charro', 'Traje charro'), ('toga', 'Toga')]), ('Ropa Especializada', [('ropa_maternidad', 'Ropa de maternidad'), ('ropa_seguridad', 'Ropa de seguridad'), ('ropa_lluvia', 'Ropa de lluvia'), ('traje_nieve', 'Traje de nieve'), ('traje_neopreno', 'Traje de neopreno')])], max_length=50)),
                ('talla', models.CharField(choices=[('0-3m', '0-3 meses'), ('3-6m', '3-6 meses'), ('6-9m', '6-9 meses'), ('9-12m', '9-12 meses'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=20)),
                ('temporada', models.CharField(choices=[('primavera', 'Primavera'), ('verano', 'Verano'), ('otono', 'Otoño'), ('invierno', 'Invierno')], default='primavera', max_length=20)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='donaciones/')),
                ('estado', models.CharField(blank=True, choices=[('activa', 'Activa'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20, null=True)),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('comuna_region', models.CharField(choices=[('', 'Seleccione una opción'), ('Región Metropolitana', [('santiago', 'Santiago'), ('maipu', 'Maipú'), ('providencia', 'Providencia'), ('las_condes', 'Las Condes'), ('ñunoa', 'Ñuñoa'), ('vitacura', 'Vitacura'), ('la_florida', 'La Florida'), ('peñalolen', 'Peñalolén'), ('el_bosque', 'El Bosque'), ('la_reina', 'La Reina'), ('pudahuel', 'Pudahuel'), ('independencia', 'Independencia'), ('san_miguel', 'San Miguel'), ('san_joaquin', 'San Joaquín'), ('macul', 'Macul')]), ('Región de Valparaíso', [('valparaiso', 'Valparaíso'), ('vina_del_mar', 'Viña del Mar'), ('quillota', 'Quillota'), ('san_antonio', 'San Antonio'), ('san_felipe', 'San Felipe'), ('villa_alegre', 'Villa Alegre'), ('almargen', 'Almargen'), ('almendral', 'Almendral'), ('cachagua', 'Cachagua'), ('zapallar', 'Zapallar')]), ('Región de Coquimbo', [('la_serena', 'La Serena'), ('coquimbo', 'Coquimbo'), ('combarbala', 'Combarbalá'), ('illapel', 'Illapel'), ('andacollo', 'Andacollo'), ('punitaqui', 'Punitaqui'), ('ovalle', 'Ovalle'), ('punta_arenas', 'Punta Arenas'), ('peñuelas', 'Peñuelas')]), ('Región de Antofagasta', [('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('mejillones', 'Mejillones'), ('tocopilla', 'Tocopilla'), ('sierra_gorda', 'Sierra Gorda'), ('maria_elena', 'María Elena')]), ('Región de Atacama', [('copiapo', 'Copiapó'), ('vallenar', 'Vallenar'), ('chilecito', 'Chilecito'), ('caldera', 'Caldera'), ('huasco', 'Huasco'), ('freirina', 'Freirina')]), ('Región de Araucanía', [('temuco', 'Temuco'), ('angol', 'Angol'), ('villarrica', 'Villarrica'), ('pitrufquen', 'Pitrufquén'), ('freire', 'Freire'), ('carahue', 'Carahue'), ('teodoro_schmidt', 'Teodoro Schmidt'), ('lachauco', 'Lachauco')]), ('Región de Los Ríos', [('valdivia', 'Valdivia'), ('la_union', 'La Unión'), ('rio_negro', 'Río Negro'), ('corral', 'Corral'), ('los_lagos', 'Los Lagos'), ('llanquihue', 'Llanquihue')]), ('Región de Los Lagos', [('osorno', 'Osorno'), ('puerto_montt', 'Puerto Montt'), ('castro', 'Castro'), ('ancud', 'Ancud'), ('puyehue', 'Puyehue'), ('los_muermos', 'Los Muermos'), ('maullín', 'Maullín')]), ('Región de Magallanes', [('punta_arenas', 'Punta Arenas'), ('porvenir', 'Porvenir'), ('cabo_de_hornos', 'Cabo de Hornos'), ('primavera', 'Primavera'), ('serrano', 'Serrano')]), ('Región de Arica y Parinacota', [('arica', 'Arica'), ('putre', 'Putre'), ('camarones', 'Camarones')]), ('Región de Tarapacá', [('iquique', 'Iquique'), ('alto_hospicio', 'Alto Hospicio'), ('pica', 'Pica'), ('migración', 'Migración')]), ('Región de Antofagasta', [('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('mejillones', 'Mejillones'), ('tocopilla', 'Tocopilla'), ('sierra_gorda', 'Sierra Gorda')]), ('Región de Ñuble', [('chillan', 'Chillán'), ('bulnes', 'Bulnes'), ('quillan', 'Quillán'), ('yungay', 'Yungay')])], default='', max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('logotipo', models.ImageField(blank=True, default='img/nofoto.jpg', null=True, upload_to='fundaciones/')),
                ('sitio_web', models.URLField(blank=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='aplicacion.conversacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('respuesta', models.TextField(choices=[('PETICION', 'PETICION'), ('DONACION', 'DONACION')], default='')),
                ('idid', models.TextField()),
                ('tipo', models.TextField(choices=[('PETICION', 'PETICION'), ('DONACION', 'DONACION')], default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_ropa', models.CharField(choices=[('', 'Seleccione una opción'), ('Ropa Superior', [('camiseta', 'Camiseta'), ('polo', 'Polo'), ('blusa', 'Blusa'), ('camisa', 'Camisa'), ('top', 'Top'), ('sueter', 'Suéter'), ('sudadera', 'Sudadera'), ('chaqueta', 'Chaqueta'), ('abrigo', 'Abrigo'), ('cardigan', 'Cárdigan'), ('chaleco', 'Chaleco'), ('camiseta_sin_mangas', 'Camiseta sin mangas'), ('blazer', 'Saco o Blazer'), ('jersey', 'Jersey')]), ('Ropa Inferior', [('pantalon', 'Pantalón'), ('falda', 'Falda'), ('shorts', 'Shorts'), ('bermudas', 'Bermudas'), ('leggings', 'Leggings'), ('capris', 'Capris')]), ('Vestidos', [('vestido_fiesta', 'Vestido de Fiesta'), ('vestido_casual', 'Vestido Casual'), ('vestido_noche', 'Vestido de Noche'), ('vestido_largo', 'Vestido Largo'), ('vestido_corto', 'Vestido Corto'), ('vestido_coctel', 'Vestido de Cóctel'), ('maxi_vestido', 'Maxi Vestido')]), ('Ropa Íntima', [('sujetador', 'Sujetador'), ('calzoncillos', 'Calzoncillos'), ('bragas', 'Bragas'), ('bodysuit', 'Bodysuit'), ('camiseta_interior', 'Camiseta interior'), ('faja', 'Faja'), ('corset', 'Corset'), ('camison', 'Camisón'), ('pijama', 'Pijamas'), ('batas_dormir', 'Batas de dormir')]), ('Ropa de Exterior', [('abrigo', 'Abrigo'), ('chaqueta', 'Chaqueta'), ('gabardina', 'Gabardina o Trench'), ('parka', 'Parka'), ('poncho', 'Poncho'), ('capa', 'Capa'), ('impermeable', 'Impermeable'), ('chaleco_acolchado', 'Chaleco acolchado')]), ('Ropa Deportiva', [('sudadera', 'Sudadera'), ('pantalon_deportivo', 'Pantalón deportivo'), ('shorts_deportivos', 'Shorts deportivos'), ('leggings_deportivos', 'Leggings deportivos'), ('top_deportivo', 'Top deportivo'), ('traje_bano', 'Traje de baño'), ('bikini', 'Bikini'), ('ropa_ciclismo', 'Ropa de ciclismo'), ('ropa_yoga', 'Ropa de yoga')]), ('Ropa de Bebé', [('body', 'Body'), ('pelele', 'Pelele'), ('mameluco', 'Mameluco'), ('babero', 'Babero'), ('pantalones_bebe', 'Pantalones para bebé'), ('conjuntos_bebe', 'Conjuntos'), ('polainas', 'Polainas'), ('pijamas_bebe', 'Pijamas para bebé'), ('chaleco_acolchado_bebe', 'Chaleco acolchado para bebé')]), ('Trajes', [('traje_dos_piezas', 'Traje de dos piezas'), ('esmoquin', 'Esmoquin'), ('traje_tres_piezas', 'Traje de tres piezas'), ('conjunto_falda', 'Conjunto de falda y chaqueta'), ('conjunto_pantalon', 'Conjunto de pantalón y top')]), ('Accesorios de Ropa', [('bufanda', 'Bufanda'), ('guantes', 'Guantes'), ('sombrero', 'Sombrero'), ('cinturon', 'Cinturón'), ('panuelo', 'Pañuelo'), ('calcetines', 'Calcetines'), ('ligas', 'Ligas'), ('chal', 'Chal')]), ('Uniformes', [('uniforme_escolar', 'Uniforme escolar'), ('uniforme_trabajo', 'Uniforme de trabajo'), ('ropa_enfermeria', 'Ropa de enfermería'), ('uniforme_deportivo', 'Uniforme deportivo'), ('traje_proteccion', 'Traje de protección'), ('uniforme_militar', 'Uniforme militar')]), ('Trajes Tradicionales', [('kimono', 'Kimono'), ('sari', 'Sari'), ('traje_folclorico', 'Traje folclórico'), ('traje_flamenco', 'Traje de flamenco'), ('traje_charro', 'Traje charro'), ('toga', 'Toga')]), ('Ropa Especializada', [('ropa_maternidad', 'Ropa de maternidad'), ('ropa_seguridad', 'Ropa de seguridad'), ('ropa_lluvia', 'Ropa de lluvia'), ('traje_nieve', 'Traje de nieve'), ('traje_neopreno', 'Traje de neopreno')])], default='', max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('donador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peticiones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id_reporte', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('SPAM', 'Spam'), ('ACOSO', 'Acoso'), ('CONTENIDO_INAPROPIADO', 'Contenido Inapropiado'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('resultado', models.CharField(max_length=250)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Usuario',
                'verbose_name_plural': 'Reportes de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_resena', models.UUIDField(primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reseña', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueñoreseña', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueñoperfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
