# Generated by Django 5.1.1 on 2024-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='respuesta',
            field=models.TextField(choices=[('SI', 'SI'), ('NO', 'NO'), ('PENDIENTE', 'PENDIENTE')], default=''),
        ),
    ]
