# Generated by Django 5.1.1 on 2024-10-29 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='logotipo',
            field=models.ImageField(blank=True, default='img/nofoto.jpg', null=True, upload_to='fundaciones/'),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='donador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='img/nofoto.jpg', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('usuario1', 'usuario2')},
        ),
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('SPAM', 'Spam'), ('ACOSO', 'Acoso'), ('CONTENIDO_INAPROPIADO', 'Contenido Inapropiado'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Usuario',
                'verbose_name_plural': 'Reportes de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_resena', models.UUIDField(primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reseña', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueñoreseña', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueñoperfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
