# Generated by Django 5.1.1 on 2024-09-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='correo',
        ),
    ]
