# Generated by Django 5.1.1 on 2024-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='comuna_region',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Región Metropolitana', [('santiago', 'Santiago'), ('maipu', 'Maipú'), ('providencia', 'Providencia'), ('las_condes', 'Las Condes'), ('ñunoa', 'Ñuñoa'), ('vitacura', 'Vitacura'), ('la_florida', 'La Florida'), ('peñalolen', 'Peñalolén'), ('el_bosque', 'El Bosque'), ('la_reina', 'La Reina'), ('pudahuel', 'Pudahuel'), ('independencia', 'Independencia'), ('san_miguel', 'San Miguel'), ('san_joaquin', 'San Joaquín'), ('macul', 'Macul')]), ('Región de Valparaíso', [('valparaiso', 'Valparaíso'), ('vina_del_mar', 'Viña del Mar'), ('quillota', 'Quillota'), ('san_antonio', 'San Antonio'), ('san_felipe', 'San Felipe'), ('villa_alegre', 'Villa Alegre'), ('almargen', 'Almargen'), ('almendral', 'Almendral'), ('cachagua', 'Cachagua'), ('zapallar', 'Zapallar')]), ('Región de Coquimbo', [('la_serena', 'La Serena'), ('coquimbo', 'Coquimbo'), ('combarbala', 'Combarbalá'), ('illapel', 'Illapel'), ('andacollo', 'Andacollo'), ('punitaqui', 'Punitaqui'), ('ovalle', 'Ovalle'), ('punta_arenas', 'Punta Arenas'), ('peñuelas', 'Peñuelas')]), ('Región de Antofagasta', [('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('mejillones', 'Mejillones'), ('tocopilla', 'Tocopilla'), ('sierra_gorda', 'Sierra Gorda'), ('maria_elena', 'María Elena')]), ('Región de Atacama', [('copiapo', 'Copiapó'), ('vallenar', 'Vallenar'), ('chilecito', 'Chilecito'), ('caldera', 'Caldera'), ('huasco', 'Huasco'), ('freirina', 'Freirina')]), ('Región de Araucanía', [('temuco', 'Temuco'), ('angol', 'Angol'), ('villarrica', 'Villarrica'), ('pitrufquen', 'Pitrufquén'), ('freire', 'Freire'), ('carahue', 'Carahue'), ('teodoro_schmidt', 'Teodoro Schmidt'), ('lachauco', 'Lachauco')]), ('Región de Los Ríos', [('valdivia', 'Valdivia'), ('la_union', 'La Unión'), ('rio_negro', 'Río Negro'), ('corral', 'Corral'), ('los_lagos', 'Los Lagos'), ('llanquihue', 'Llanquihue')]), ('Región de Los Lagos', [('osorno', 'Osorno'), ('puerto_montt', 'Puerto Montt'), ('castro', 'Castro'), ('ancud', 'Ancud'), ('puyehue', 'Puyehue'), ('los_muermos', 'Los Muermos'), ('maullín', 'Maullín')]), ('Región de Magallanes', [('punta_arenas', 'Punta Arenas'), ('porvenir', 'Porvenir'), ('cabo_de_hornos', 'Cabo de Hornos'), ('primavera', 'Primavera'), ('serrano', 'Serrano')]), ('Región de Arica y Parinacota', [('arica', 'Arica'), ('putre', 'Putre'), ('camarones', 'Camarones')]), ('Región de Tarapacá', [('iquique', 'Iquique'), ('alto_hospicio', 'Alto Hospicio'), ('pica', 'Pica'), ('migración', 'Migración')]), ('Región de Antofagasta', [('antofagasta', 'Antofagasta'), ('calama', 'Calama'), ('mejillones', 'Mejillones'), ('tocopilla', 'Tocopilla'), ('sierra_gorda', 'Sierra Gorda')]), ('Región de Ñuble', [('chillan', 'Chillán'), ('bulnes', 'Bulnes'), ('quillan', 'Quillán'), ('yungay', 'Yungay')])], default='', max_length=50),
        ),
    ]
