# Generated by Django 5.1.1 on 2024-11-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundacion',
            name='correo',
        ),
    ]
