# Generated by Django 5.1.1 on 2024-10-13 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='donador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
