# Generated by Django 5.1.1 on 2024-10-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_peticion_donador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('usuario1', 'usuario2')},
        ),
    ]
