# Generated by Django 5.1.1 on 2024-10-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
    ]
